// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://njrwraajdusuhmcglsqo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5qcndyYWFqZHVzdWhtY2dsc3FvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5ODYxNTIsImV4cCI6MjA2NTU2MjE1Mn0.N_6uXe8T3rmgDUhVYOEkhvaJMxCmuHhKVnL4muT_dnU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);